export interface User {
  email: string;
}

export enum SocketEvent {
  GET_ALL_MESSAGES = 'GET_ALL_MESSAGES',
  SELECTED_USER_MESSAGES = 'SELECTED_USER_MESSAGES',
  ACTIVE_USERS = 'ACTIVE_USERS',
  MESSAGE = 'MESSAGE',
  NEW_USER_CONNECTED = 'NEW_USER_CONNECTED',
  USER_DISCONNECTED = 'USER_DISCONNECTED',
  BLOCK_USER = 'BLOCK_USER',
  BLACK_LIST = 'BLACK_LIST',
  BLACK_LISTERS = 'BLACK_LISTERS',
  BLOCKED = 'BLOCKED',
}
